### PR TITLE
Quick example

### PR DESCRIPTION
**Pull request by monfera**
A first, rough example. There's still a bit of code to extract out, and more importantly, there's no data layer yet - it expects prefilled JSONs (ie. the `x` etc. attributes already having the arrays, and also `xsrc` etc. to link col names together) - so no equivalent of the `grid` yet.

This runs in any browser just by loading `example/index.html`.

crosslink-plotly js example

cc @jackparmer 

PS. for the next period I'd merge own PRs without review, it's just to show the changes, and ask for review after additions.

### CODE REVIEW

**Comment by jefffriesen** [comment]
I'm really curious about this repo. As a heavy user of dc.js, I am interested in some more flexible, modern and more chart types (especially with Plotly charts). Do you have a roadmap you would want to share for this?

**Comment by jackparmer** [comment]
Hey @jefffriesen - 
Roadmap is [here](https://github.com/plotly/public-health/blob/master/README.md#roadmap
), along with some crossfilter examples hosted on plot.ly. This repo is [item 3](https://github.com/plotly/public-health/blob/master/README.md#3-open-source-plotlyjs-crossfilter-library) in that roadmap.

**Comment by jackparmer** [comment]
💃

**Comment by monfera** [comment]
Now with histograms and legends too (the upcoming `plotly.js` bundle, included here, has selection data on brush events):

histograms

**Pull request merged**
